### PR TITLE
Handle received data asynchronously

### PR DESCRIPTION
**Pull request by benzrf**
See #92.

### CODE REVIEW

**Comment by dblock** [comment]
Can you please update CHANGELOG. Could use a test maybe too?

**Comment by dblock** [comment]
The build is breaking for some other reason (something wrong with `vcr`, possibly just need to lock down that one to a previous release - can you please check it out - I am happy to fix if it's too difficult).

**Comment by benzrf** [comment]
What kind of test could I write that wouldn't be extremely nondeterministic?

**Comment by dblock** [comment]
I would just make sure that the function implemented by the bot command is invoked via `async`, so somewhere I'd have something like `expect(...).to receive(:async).and_...`. But if it's too complicated it's fine without it.

**Comment by benzrf** [comment]
Oh, I could probably have the first command sleep indefinitely for the test. I'll try implementing that soon.

**Comment by benzrf** [comment]
OK, it looks like it'd be fairly complicated to write a test. I *might* be able to figure something out, but it'd definitely take a lot of digging and learning about how the library and its tests are set up.

**Comment by dblock** [comment]
This looks good. Could you please try to fix the build or let me know if you can't?

**Comment by benzrf** [comment]
It looks like the issue is with `vcr` - there was a new minor version released today.

**Comment by benzrf** [comment]
https://github.com/vcr/vcr/issues/582

**Comment by dblock** [comment]
Lock vcr to 3.0.1 in this PR?

**Comment by benzrf** [comment]
ok - but it seems like kind of an innapropriate place to do it.

**Comment by benzrf** [comment]
The issue on the vcr repo suggests that this should fix it too

**Comment by benzrf** [comment]
ok nvm, I'll just fix the vcr version.

**Comment by dblock** [comment]
Ha, it's now failing with another issue around bundler. That's https://github.com/bundler/bundler/issues/3558 and the fix is to update bundler:

```ruby
before_install:
   - gem update bundler
```

Please. I just want this build to be green.

**Comment by benzrf** [comment]
Wait - would you prefer that I lock the vcr version, or add bundler update as well?

**Comment by dblock** [comment]
Honestly I don't have a preference. It's just mechanics.

**Comment by benzrf** [comment]
The build is passing

**Comment by dblock** [comment]
Merged, thanks.

**Pull request merged**
