### PR TITLE
Updating Celluloid logger reference

### PR DESCRIPTION
**Pull request by jlyonsmith**

### CODE REVIEW

**Comment by dblock** [comment]
First question, why is the integration test succeeding without this change?

**Comment by jlyonsmith** [comment]
I don't see celluloid or celluloid-io pulled in by the .gemspec file (which makes sense as you are trying to dynamically support either one)  Therefore you must have an older version installed on your dev box.

**Comment by dblock** [comment]
Hm, nope, https://travis-ci.org/dblock/slack-ruby-client/jobs/101613182#L107 has pulled in 0.17.2.

screen shot 2016-01-11 at 10 56 55 am

Locally you can run `rm Gemfile.lock ; CONCURRENCY=celluloid-io SLACK_API_TOKEN=... bundle`, then `CONCURRENCY=celluloid-io SLACK_API_TOKEN=... rspec spec/integration`.

What do you see when you run this?

**Comment by jlyonsmith** [comment]
I see 2 successful tests.   What do you see with my merge?

[RSpec.txt](https://github.com/dblock/slack-ruby-client/files/86053/RSpec.txt)

**Comment by dblock** [comment]
I am saying that even without your merge I am seeing 2 successful tests.

**Comment by jlyonsmith** [comment]
You could try integrating slack-ruby-client into a new project with Celluloid and Reel and see what happens when you try and run it.  It's definitely the case that [the current version of Celluloid uses Celluloid::Internal::Logging](https://github.com/celluloid/celluloid/wiki/DEPRECATION-WARNING#most-common-changes)

**Comment by dblock** [comment]
So what happens when you try to run it? What output do you get?

I know this is a trivial change and it seems like it's the right thing, I am just trying to understand what's going on, not being annoying :) I'd like a test that reproduces whatever error you're getting.

**Comment by jlyonsmith** [comment]
This reproduces the problem.  Just run `bundle ; SLACK_API_TOKEN=... ruby main.rb` 

Isn't [`spec_helper.rb`](https://github.com/dblock/slack-ruby-client/blob/master/spec/spec_helper.rb) missing `require 'bundler/setup'`?

[test-ruby-slack-client.tar.gz](https://github.com/dblock/slack-ruby-client/files/86277/test-ruby-slack-client.tar.gz)

**Comment by dblock** [comment]
I figured it out, Celluiloid docs say in https://github.com/celluloid/celluloid:

screen shot 2016-01-11 at 4 57 11 pm

You did `require celluloid/current`, which caused a subsequent `require celluloid/io` not to load the "backported" mode. Adding that on top of celluloid.rb in slack-ruby-client reproduced the issue.

Fixed in https://github.com/dblock/slack-ruby-client/commit/33360aaf947204f6d4a213a2dbbba43f5c5af42d. Can you try with `gem 'slack-ruby-client', github: 'dblock/slack-ruby-client'` to confirm? I'll cut a release then.

**Comment by jlyonsmith** [comment]
Confirmed that I everything builds fine now.  Thanks!

On Mon, Jan 11, 2016 at 2:10 PM, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> I figured it out, Celluiloid docs say in
> https://github.com/celluloid/celluloid:
>
> [image: screen shot 2016-01-11 at 4 57 11 pm]
> <https://cloud.githubusercontent.com/assets/542335/12247945/68cd5410-b884-11e5-81d8-317444678a60.png>
>
> You did require celluloid/current, which caused a subsequent require
> celluloid/io not to load the "backported" mode. Adding that on top of
> celluloid.rb in slack-ruby-client reproduced the issue.
>
> Fixed in 33360aa
> <https://github.com/dblock/slack-ruby-client/commit/33360aaf947204f6d4a213a2dbbba43f5c5af42d>.
> Can you try with gem 'slack-ruby-client', github:
> 'dblock/slack-ruby-client' to confirm? I'll cut a release then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dblock/slack-ruby-client/pull/47#issuecomment-170707505>
> .
>



-- 
John Lyon-Smith
john@lyon-smith.org
@jlyonsmith
360 860 1883

**Comment by dblock** [comment]
@jlyonsmith I cut 0.5.3, thanks for your help.

**Pull request closed without merging**
