### PR TITLE
Fix usergroups apis

### PR DESCRIPTION
**Pull request by masatomo**
* fix usergroups_users_update API
* add usergroups_users_list API

### CODE REVIEW

**Comment by dblock** [comment]
These are auto-generated files. Did you make these changes manually?

Slack Web API is updated from https://github.com/dblock/slack-api-ref, a maintained, machine-readable version of Slack API Docs, generated by scraping api.slack.com. To update the Web API from the latest definition run the following Rake task: `rake slack:api:update`. 

Also please update CHANGELOG.

**Comment by masatomo** [comment]
ah, I didn't know about it. let me fix it.

**Comment by dblock** [comment]
I do call this out in contributing, but I wonder whether there's something else we can/need to do to help people not modify these files. Maybe expand the note on top of the files that currently says `# This file was auto-generated by lib/tasks/web.rake`.

**Comment by masatomo** [comment]
i'll create another pull-request.

**Pull request closed without merging**
